repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
        name: Ruff Formatter
        types_or:
          - python
          - pyi
          - jupyter
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        args:
          - --no-strict-optional
          - --ignore-missing-imports
          - --implicit-optional
          - --install-types
        files: ^(src/)
        additional_dependencies: [types-requests]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: .*\.json
      - id: trailing-whitespace
      - id: check-ast
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-executables-have-shebangs
      - id: name-tests-test
        args:
          - --pytest-test-first
        exclude: ^tests/mocks|^tests/utils|^tests/plugins|^tests/fixtures|.*\.ipynb
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
        exclude: ^tests/mocks|Pipfile*
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]
