[tool.black]
line-length = 110

[tool.isort]
profile = "black"
line_length = 110


[tool.mypy]
# mypy_path = 'src'
exclude = ["config"]
files  = '*.py'
warn_return_any = true
warn_unused_configs = true