[tool.pytest.ini_options]
pythonpath = "./src"
filterwarnings = "ignore:.*:DeprecationWarning"
addopts = "--cov --cov-report=lcov:lcov.info --cov-report=term"
markers = []

[tool.coverage.run]
source = ["src"]

[tool.ruff]
line-length = 100
lint.select = ["F401"]  # Rule for unused imports


[tool.mypy]
# mypy_path = 'src'
exclude = ["config"]
files  = '*.py'
warn_return_any = true
warn_unused_configs = true

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "SS05",
    "EX01",
    "SA01",
]
